services:
  - type: web
    name: backend-server
    env: node
    buildCommand: |
      apt-get update && apt-get install -y python3 python3-pip  
      pip3 install -r requirements.txt
      npm install
    startCommand: npm start
    plan: free
